In [2]:
import numpy as np

# Creating Array from scratch

In [7]:
zeros = np.zeros((3,4))
print('zeros array:\n',zeros)

ones = np.ones ((2,3))
print('ones array:\n',ones)

full = np.full((2,2),4)
print('full array:\n',full)

random = np.random.random((2,3))
print('random array:\n',random)

sequnce = np.arange(0,10,2) 
print('sequence array:\n',sequnce)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[4 4]
 [4 4]]
random array:
 [[0.10469294 0.32592778 0.08974362]
 [0.44766074 0.84004778 0.48919627]]
sequence array:
 [0 2 4 6 8]


# Vetor,Matrix and Tensor

In [13]:
#vector
vector = np.array([1,2,3])
print('vector:',vector)

#matric
matric = np.array([[1,3,4],
                 [1,2,3]])
print('matric:',matric)

#tensor
tensor = np.array([[[1,2,],[3,4]],
                  [[5,6],[7,8]]])
print('tensor',tensor)

vector: [1 2 3]
matric: [[1 3 4]
 [1 2 3]]
tensor [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Properties of array

In [17]:
arr = np.array([[1,2],[3,4]])
print('shape',arr.shape)
print('dimension',arr.ndim)
print('size',arr.size)
print('datatype',arr.dtype)

shape (2, 2)
dimension 2
size 4
datatype int64


# array reshaping

In [30]:
arr = np.arange(12)
print ('original array:',arr)

reshaped = arr.reshape((3,4))
print('reshaped array :',reshaped )

flattened = reshaped.flatten()
print('\n flattenend array:',flattened)

#ravel(return view instent of copy)
raveled = reshaped.ravel()
print('\n ravel array:',raveled)

#transpose
transpose = reshaped.T
print('\n transpose array:',transpose)


original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattenend array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 ravel array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transpose array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
