# Numpy array operations

In [14]:
import numpy as np

# slicing and indexing on 1D array

In [15]:
arr = np.arange((12))
#[0,1,2,3,4,5,6,7,8,9,10,11]
print('basic slicing : ',arr[2:7])
print('with step :',arr[1:8:2])
print('negative indexing:',arr[-3])

basic slicing :  [2 3 4 5 6]
with step : [1 3 5 7]
negative indexing: 9


# 2D array

In [16]:
arr_2 = np.array([[1,2,3],     #0
                  [4,5,6],     #1
                  [7,8,9]])    #2

print('specific element:',arr_2[1,2]) #row ,element
print('entire row :',arr_2[1])
print('entire colunm :',arr_2[:,1])


specific element: 6
entire row : [4 5 6]
entire colunm : [2 5 8]


# Sorting


In [17]:
#1D array
unsorted = np.array([3 ,2 ,5 ,6 ,8 ,7 ,9 ,4])
print('unsorted array:',unsorted)
print('sorted array :',np.sort(unsorted))

#2D array
arr_2d_unsorted = ([[3,1],[1,2],[2,3]])
print('unsorted 2d array :',arr_2d_unsorted)
print('sorted 2d array by column :',np.sort(arr_2d_unsorted,axis=0))

unsorted array: [3 2 5 6 8 7 9 4]
sorted array : [2 3 4 5 6 7 8 9]
unsorted 2d array : [[3, 1], [1, 2], [2, 3]]
sorted 2d array by column : [[1 1]
 [2 2]
 [3 3]]


# Filter

In [18]:
#1d
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers %2 == 0]
print('even number:',even_number)

even number: [ 2  4  6  8 10]


# Filter with mask

In [19]:
mask = numbers > 5
print('Number greater than 5',numbers[mask])

Number greater than 5 [ 6  7  8  9 10]


# fancy indexing vs np.where

In [22]:
indices =[1,3,5]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print('np where ',numbers[where_result])


[2 4 6]
(array([5, 6, 7, 8, 9]),)
np where  [ 6  7  8  9 10]


In [30]:
condition_array = np.where(numbers > 5 ,numbers,numbers)
print(condition_array)

condition_array = np.where(numbers > 5 ,numbers*2,numbers)
print(condition_array)

condition_array = np.where(numbers > 5 ,"true","false")
print(condition_array)

"""if(numbers > 5){
    numbers*2
}else{
    nubers
} """

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5 12 14 16 18 20]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


'if(numbers > 5){\n    numbers*2\n}else{\n    nubers\n} '

# Adding and removing data and merging

# #  merging 

In [31]:
#marge
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)



[1 2 3 4 5 6]


## array compability

# ##  adding 

In [33]:
#case1
a = np.array([1,2,3])
b = np.array([4,5,6])

print ('capability:',a.shape == b.shape)

#case2
a = np.array([1,2,3])
b = np.array([4,5,6,7])

print ('capability:',a.shape == b.shape)


capability: True
capability: False


# # removing

In [40]:
#for row
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row =np.vstack((original,new_row))
print('original:',original)
print('row:',with_new_row)


#for col
new_col = np.array([[5],[6]])
with_new_col = np.hstack((original,new_col))
print('colunm:',with_new_col)



original: [[1 2]
 [3 4]]
row: [[1 2]
 [3 4]
 [5 6]]
colunm: [[1 2 5]
 [3 4 6]]


In [41]:
arr = np.array([1,2,7,3,4,5,])
deleted = np.delete(arr,2)
print(deleted)

[1 2 3 4 5]
